### ISSUE TITLE
is this alright?

### ISSUE THREAD

**Issue by Hemiptelea** [ROFLailXGOD/twitch-farmer#4]
'utf-8' codec can't decode byte 0xd0 in position 1407: unexpected end of data
'utf-8' codec can't decode byte 0xbe in position 0: invalid start byte
'utf-8' codec can't decode bytes in position 1405-1407: unexpected end of data
'utf-8' codec can't decode byte 0x82 in position 0: invalid start byte

When I run this script, these messages are output. Is it normal?
And is there a way to only watch broadcasts in certain languages?

**Comment by ROFLailXGOD** [comment]
Yeah, you can just ignore these messages, they don't do anything harmful. I might look into it one day, but too I'm busy right now.

**Comment by queechy** [comment]
okay, and is there a way to only watch broadcasts in certain languages?

**Comment by Hemiptelea** [comment]
> Yeah, you can just ignore these messages, they don't do anything harmful. I might look into it one day, but too I'm busy right now.

okay, and is there a way to only watch broadcasts in certain languages?

**Comment by ROFLailXGOD** [comment]
> > Yeah, you can just ignore these messages, they don't do anything harmful. I might look into it one day, but too I'm busy right now.
> 
> okay, and is there a way to only watch broadcasts in certain languages?

No

**Comment by ROFLailXGOD** [comment]
I'm closing the issue, but if you have any other questions, feel free to continue this thread
