### ISSUE TITLE
Shows "Collected 0 channels to connect to" if the MAX_VIEWERS value is set below 4000

### ISSUE THREAD

**Issue by pewpasta** [ROFLailXGOD/twitch-farmer#6]
But ,it works fine if the MAX_VIEWERS value is set to something high like 20000
![image](https://user-images.githubusercontent.com/67459484/104741455-3fe6aa80-576f-11eb-8952-817c748aa3da.png)

**Comment by ROFLailXGOD** [comment]
That's weird. I think I never used more than 4000. I'll look into it a bit later

**Comment by ROFLailXGOD** [comment]
Thanks for the report! Should be fixed now. 11d44fa0b0d88efce90dc69f40ed67b332940791
