### ISSUE TITLE
App stops sending pings

### ISSUE THREAD

**Issue by ghost** [ROFLailXGOD/twitch-farmer#8]
It doesn't seem to be sending "PONG's" or refreshing the channel list for me. Thought I managed to get it working but it stopped after just one. Does the cmd need to be the active window all of the time?
![pong](https://user-images.githubusercontent.com/81125408/111997762-a6939600-8b1b-11eb-8817-0bedf3d3a6ab.png)

**Comment by ROFLailXGOD** [comment]
As it is mentioned in the "Disclaimer" section:
> There's also no "connection lost" situations handling.

How many channels are you connecting to and what are min/max viewers values?

**Comment by ghost** [comment]
This was done using the default values:
MAX_CONNECTIONS = 200
MIN_VIEWERS = 250
MAX_VIEWERS = 3000
However, I've since lowered max connections to 100 and it does appear to be working now. I'll try experimenting with different values. Thanks for the quick response, closing the issue.

**Comment by ROFLailXGOD** [comment]
No problem. Good luck with farming :)
